import chokidar from 'chokidar';
import { ChromaClient } from 'chromadb';
import { RecursiveCharacterTextSplitter } from '@langchain/textsplitters';
import { Ollama } from 'ollama';
import fs from 'fs-extra';
import * as dotenv from 'dotenv';
import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pdfParse = require('pdf-parse');

dotenv.config();

// Configuration
const OLLAMA_HOST = process.env.OLLAMA_HOST || 'http://127.0.0.1:11434';
const CHROMA_URL = process.env.CHROMA_URL || 'http://localhost:8000';
const WATCH_DIR = './documents';
const COLLECTION_NAME = 'aura_docs';
const EMBED_MODEL = process.env.EMBED_MODEL || 'nomic-embed-text:latest';

// Initialize Clients
const chroma = new ChromaClient({ path: CHROMA_URL });
const ollama = new Ollama({ host: OLLAMA_HOST });

function getProjectName(filePath) {
    const relative = path.relative(path.resolve(WATCH_DIR), path.resolve(filePath));
    const parts = relative.split(path.sep);
    return parts.length > 1 ? parts[0] : 'root';
}

// Custom Embedder for ChromaDB using Ollama
const ollamaEmbedder = {
    generate: async (texts) => {
        const embeddings = [];
        for (const text of texts) {
            const response = await ollama.embeddings({
                model: EMBED_MODEL,
                prompt: text
            });
            embeddings.push(response.embedding);
        }
        return embeddings;
    }
};

async function getCollection() {
    return await chroma.getOrCreateCollection({
        name: COLLECTION_NAME,
        embeddingFunction: ollamaEmbedder,
        metadata: { "hnsw:space": "cosine" }
    });
}

// Process and insert a file into Chroma
async function processFile(filePath) {
    const ext = path.extname(filePath).toLowerCase();
    if (ext !== '.txt' && ext !== '.md' && ext !== '.pdf') {
        return;
    }

    console.log(`[+] Processing file: ${filePath}`);
    try {
        const collection = await getCollection();
        
        // 1. Delete existing vectors for this specific file path to avoid duplicates
        console.log(`[ ] Removing old embeddings for ${filePath}...`);
        try {
            await collection.delete({ where: { "source": filePath } });
        } catch (e) {
            // Ignore error
        }

        // 2. Read file content

        let content = '';
        if (ext === '.pdf') {
            const dataBuffer = await fs.readFile(filePath);
            const pdfData = await pdfParse(dataBuffer);
            content = pdfData.text;
        } else {
            content = await fs.readFile(filePath, 'utf-8');
        }

        if (!content.trim()) return;

        // 3. Split content into logical chunks
        const splitter = new RecursiveCharacterTextSplitter({
            chunkSize: 500,
            chunkOverlap: 50,
        });
        const chunks = await splitter.createDocuments([content]);
        if (chunks.length === 0) return;

        console.log(`[ ] Generating ${chunks.length} embeddings for ${filePath}...`);
        const ids = [];
        const metadatas = [];
        const documents = [];

        for (let i = 0; i < chunks.length; i++) {
            ids.push(`${filePath}-chunk-${i}`);
            metadatas.push({
                source: filePath,
                project: getProjectName(filePath),
                chunk_index: i,
                timestamp: new Date().toISOString()
            });
            documents.push(chunks[i].pageContent);
        }

        // 4. Insert into ChromaDB (embeddings auto-generated by ollamaEmbedder)
        await collection.upsert({
            ids: ids,
            metadatas: metadatas,
            documents: documents
        });

        console.log(`[+] Successfully synched ${filePath} to ChromaDB!`);

    } catch (error) {
        console.error(`[!] Error processing file ${filePath}:`, error.message || error);
    }
}

// Handle file deletion
async function removeFile(filePath) {
    console.log(`[-] File deleted. Removing vectors for: ${filePath}`);
    try {
        const collection = await getCollection();
        await collection.delete({ where: { "source": filePath } });
        console.log(`[+] Successfully removed ${filePath} from ChromaDB.`);
    } catch (error) {
        console.error(`[!] Error removing file ${filePath}:`, error.message || error);
    }
}

// Initialize Watcher
async function startWatcher() {
    console.log(`Starting Aura Watcher on directory: ${WATCH_DIR}`);
    console.log(`Ollama Host: ${OLLAMA_HOST}`);
    console.log(`ChromaDB URL: ${CHROMA_URL}`);

    // Ensure documents dir exists
    await fs.ensureDir(WATCH_DIR);

    const watcher = chokidar.watch(WATCH_DIR, {
        persistent: true,
        ignored: /(^|[\/\\])\../, // ignore dotfiles and dot folders like .aura
        ignoreInitial: false, // Process existing files on startup
        awaitWriteFinish: {
            stabilityThreshold: 2000,
            pollInterval: 100
        }
    });

    watcher
        .on('add', path => processFile(path))
        .on('change', path => processFile(path))
        .on('unlink', path => removeFile(path))
        .on('error', error => console.error(`Watcher error: ${error}`));
}

startWatcher().catch(console.error);
